In [54]:
import pandas as pd
import numpy as np

df = pd.read_excel("data/raw/railway.xlsx")

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

Dataset loaded successfully!
Dataset shape: (31653, 18)

In [55]:
df.head()

,Transaction ID,Date of Purchase,Time of Purchase,Purchase Type,Payment Method,Railcard,Ticket Class,Ticket Type,Price,Departure Station,Arrival Destination,Date of Journey,Departure Time,Arrival Time,Actual Arrival Time,Journey Status,Reason for Delay,Refund Request
0,da8a6ba8-b3dc-4677-b176,2023-12-08,12:41:11,Online,Contactless,Adult,Standard,Advance,43,London Paddington,Liverpool Lime Street,2024-01-01,11:00:00,13:30:00,13:30:00,On Time,NaN,No
1,b0cdd1b0-f214-4197-be53,2023-12-16,11:23:01,Station,Credit Card,Adult,Standard,Advance,23,London Kings Cross,York,2024-01-01,09:45:00,11:35:00,11:40:00,Delayed,Signal Failure,No
2,f3ba7a96-f713-40d9-9629,2023-12-19,19:51:27,Online,Credit Card,NaN,Standard,Advance,3,Liverpool Lime Street,Manchester Piccadilly,2024-01-02,18:15:00,18:45:00,18:45:00,On Time,NaN,No
3,b2471f11-4fe7-4c87-8ab4,2023-12-20,23:00:36,Station,Credit Card,NaN,Standard,Advance,13,London Paddington,Reading,2024-01-01,21:30:00,22:30:00,22:30:00,On Time,NaN,No
4,2be00b45-0762-485e-a7a3,2023-12-27,18:22:56,Online,Contactless,NaN,Standard,Advance,76,Liverpool Lime Street,London Euston,2024-01-01,16:45:00,19:00:00,19:00:00,On Time,NaN,No

In [56]:
df.tail()

,Transaction ID,Date of Purchase,Time of Purchase,Purchase Type,Payment Method,Railcard,Ticket Class,Ticket Type,Price,Departure Station,Arrival Destination,Date of Journey,Departure Time,Arrival Time,Actual Arrival Time,Journey Status,Reason for Delay,Refund Request
31648,1304623d-b8b7-4999-8e9c,2024-04-30,18:42:58,Online,Credit Card,NaN,Standard,Off-Peak,4,Manchester Piccadilly,Liverpool Lime Street,2024-04-30,20:00:00,20:30:00,20:30:00,On Time,NaN,No
31649,7da22246-f480-417c-bc2f,2024-04-30,18:46:10,Online,Contactless,NaN,Standard,Off-Peak,10,London Euston,Birmingham New Street,2024-04-30,20:15:00,21:35:00,21:35:00,On Time,NaN,No
31650,add9debf-46c1-4c75-b52d,2024-04-30,18:56:41,Station,Credit Card,NaN,Standard,Off-Peak,4,Manchester Piccadilly,Liverpool Lime Street,2024-04-30,20:15:00,20:45:00,20:45:00,On Time,NaN,No
31651,b92b047c-21fd-4859-966a,2024-04-30,19:51:47,Station,Credit Card,NaN,Standard,Off-Peak,10,London Euston,Birmingham New Street,2024-04-30,21:15:00,22:35:00,22:35:00,On Time,NaN,No
31652,1d5d89a2-bde5-410f-8f91,2024-04-30,20:05:39,Station,Credit Card,Adult,Standard,Off-Peak,3,Liverpool Lime Street,Manchester Piccadilly,2024-04-30,21:30:00,22:00:00,22:00:00,On Time,NaN,No

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31653 entries, 0 to 31652
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction ID       31653 non-null  object
 1   Date of Purchase     31653 non-null  datetime64[ns]
 2   Time of Purchase     31653 non-null  object
 3   Purchase Type        31653 non-null  object
 4   Payment Method       31653 non-null  object
 5   Railcard             10735 non-null  object
 6   Ticket Class         31653 non-null  object
 7   Ticket Type          31653 non-null  object
 8   Price                31653 non-null  int64
 9   Departure Station    31653 non-null  object
 10  Arrival Destination  31653 non-null  object
 11  Date of Journey      31653 non-null  datetime64[ns]
 12  Departure Time       31653 non-null  object
 13  Arrival Time         31653 non-null  object
 14  Actual Arrival Time  29773 non-null  object
 15  Journey Status       31653 non-null  object
 16  Reason for Delay     4172 non-null   object
 17  Refund Request       31653 non-null  object
dtypes: datetime64[ns](2), int64(1), object(15)
memory usage: 4.3+ MB

In [58]:
df.describe()

,Date of Purchase,Price,Date of Journey
count,31653,31653.000000,31653
mean,2024-02-28 16:16:36.303667968,23.439200,2024-03-01 08:01:10.969576192
min,2023-12-08 00:00:00,1.000000,2024-01-01 00:00:00
25%,2024-01-30 00:00:00,5.000000,2024-01-31 00:00:00
50%,2024-03-01 00:00:00,11.000000,2024-03-01 00:00:00
75%,2024-03-31 00:00:00,35.000000,2024-03-31 00:00:00
max,2024-04-30 00:00:00,267.000000,2024-04-30 00:00:00
std,NaN,29.997628,NaN

In [59]:
df.columns

Index(['Transaction ID', 'Date of Purchase', 'Time of Purchase',
       'Purchase Type', 'Payment Method', 'Railcard', 'Ticket Class',
       'Ticket Type', 'Price', 'Departure Station', 'Arrival Destination',
       'Date of Journey', 'Departure Time', 'Arrival Time',
       'Actual Arrival Time', 'Journey Status', 'Reason for Delay',
       'Refund Request'],
      dtype='object')

In [118]:
dictionary = pd.read_excel("data/raw/railway_data_dictionary.xlsx")

with pd.option_context("display.max_colwidth", None):
    display(dictionary)

,Field,Description
0,Transaction ID,Unique identifier for an individual train ticket purchase
1,Date of Purchase,Date the ticket was purchased
2,Time of Purchase,Time the ticket was purchased
3,Purchase Type,Whether the ticket was purchased online or directly at a train station
4,Payment Method,"Payment method used to purchase the ticket (Contactles, Credit Card, or Debit Card)"
5,Railcard,"Whether the passenger is a National Railcard holder (Adult, Senior, or Disabled) or not (None). Railcard holders get 1/3 off their ticket purchases."
6,Ticket Class,Seat class for the ticket (Standard or First)
7,Ticket Type,When you bought or can use the ticket. Advance tickets are 1/2 off and must be purchased at least a day prior to departure. Off-Peak tickets are 1/4 off and must be used outside of peak hours (weekdays between 6-8am and 4-6pm). Anytime tickets are full price and can be bought and used at any time during the day.
8,Price,Final cost of the ticket
9,Departure Station,Station to board the train
10,Arrival Destination,Station to exit the train
11,Date of Journey,Date the train departed
12,Departure Time,Time the train departed
13,Arrival Time,Time the train was scheduled to arrive at its destination (can be on the day after departure)
14,Actual Arrival Time,Time the train arrived at its destination (can be on the day after departure)
15,Journey Status,"Whether the train was on time, delayed, or cancelled"
16,Reason for Delay,Reason for the delay or cancellation
17,Refund Request,Whether the passenger requested a refund after a delay or cancellation

In [61]:
df.isnull().sum()

Transaction ID             0
Date of Purchase           0
Time of Purchase           0
Purchase Type              0
Payment Method             0
Railcard               20918
Ticket Class               0
Ticket Type                0
Price                      0
Departure Station          0
Arrival Destination        0
Date of Journey            0
Departure Time             0
Arrival Time               0
Actual Arrival Time     1880
Journey Status             0
Reason for Delay       27481
Refund Request             0
dtype: int64

In [62]:
df.duplicated().sum()

np.int64(0)

In [63]:
df.nunique()

Transaction ID         31653
Date of Purchase         128
Time of Purchase       24351
Purchase Type              2
Payment Method             3
Railcard                   3
Ticket Class               2
Ticket Type                3
Price                    125
Departure Station         12
Arrival Destination       32
Date of Journey          121
Departure Time            96
Arrival Time             203
Actual Arrival Time      623
Journey Status             3
Reason for Delay           8
Refund Request             2
dtype: int64

In [64]:
categorical_columns = [
    "Purchase Type",
    "Payment Method",
    "Railcard",
    "Ticket Class",
    "Ticket Type",
    "Departure Station",
    "Arrival Destination",
    "Journey Status",
    "Reason for Delay",
    "Refund Request"
]

for column in categorical_columns:
    print("\n", "=" * 50)
    print(column)
    print("=" * 50)
    print(df[column].value_counts(dropna=False))

 ==================================================
Purchase Type
==================================================
Purchase Type
Online     18521
Station    13132
Name: count, dtype: int64

 ==================================================
Payment Method
==================================================
Payment Method
Credit Card    19136
Contactless    10834
Debit Card      1683
Name: count, dtype: int64

 ==================================================
Railcard
==================================================
Railcard
NaN         20918
Adult        4846
Disabled     3089
Senior       2800
Name: count, dtype: int64

 ==================================================
Ticket Class
==================================================
Ticket Class
Standard       28595
First Class     3058
Name: count, dtype: int64

 ==================================================
Ticket Type
==================================================
Ticket Type
Advance     17561
Off-Peak     8752
Anytime      5340
Name: count, dtype: int64

 ==================================================
Departure Station
==================================================
Departure Station
Manchester Piccadilly    5650
London Euston            4954
Liverpool Lime Street    4561
London Paddington        4500
London Kings Cross       4229
London St Pancras        3891
Birmingham New Street    2136
York                      927
Reading                   594
Oxford                    144
Edinburgh Waverley         51
Bristol Temple Meads       16
Name: count, dtype: int64

 ==================================================
Arrival Destination
==================================================
Arrival Destination
Birmingham New Street    7742
Liverpool Lime Street    5022
York                     4019
Manchester Piccadilly    3968
Reading                  3920
London Euston            1567
London St Pancras         749
Oxford                    623
London Paddington         351
Leicester                 337
Sheffield                 272
Durham                    258
Leeds                     255
Peterborough              242
Swindon                   228
Tamworth                  227
Nuneaton                  219
Doncaster                 211
Crewe                     193
Stafford                  190
Edinburgh Waverley        178
Nottingham                158
Edinburgh                 154
Bristol Temple Meads      144
Wolverhampton             115
London Kings Cross         84
London Waterloo            68
Coventry                   65
Didcot                     48
Cardiff Central            16
Wakefield                  15
Warrington                 15
Name: count, dtype: int64

 ==================================================
Journey Status
==================================================
Journey Status
On Time      27481
Delayed       2292
Cancelled     1880
Name: count, dtype: int64

 ==================================================
Reason for Delay
==================================================
Reason for Delay
NaN                   27481
Weather                 995
Technical Issue         707
Signal Failure          523
Signal failure          447
Staffing                410
Staff Shortage          399
Weather Conditions      377
Traffic                 314
Name: count, dtype: int64

 ==================================================
Refund Request
==================================================
Refund Request
No     30535
Yes     1118
Name: count, dtype: int64

In [65]:
df.groupby("Journey Status")[[
    "Actual Arrival Time",
    "Reason for Delay"
]].apply(lambda group: group.isnull().sum())

                Actual Arrival Time  Reason for Delay
Journey Status
Cancelled                      1880                 0
Delayed                           0                 0
On Time                           0             27481

In [66]:
df["Price"].describe()

count    31653.000000
mean        23.439200
std         29.997628
min          1.000000
25%          5.000000
50%         11.000000
75%         35.000000
max        267.000000
Name: Price, dtype: float64

In [67]:
(df["Date of Purchase"] > df["Date of Journey"]).sum()

np.int64(0)

In [68]:
df[[
    "Date of Purchase",
    "Time of Purchase",
    "Date of Journey",
    "Departure Time",
    "Arrival Time",
    "Actual Arrival Time"
]].dtypes

Date of Purchase       datetime64[ns]
Time of Purchase               object
Date of Journey        datetime64[ns]
Departure Time                 object
Arrival Time                   object
Actual Arrival Time            object
dtype: object

In [69]:
df[[
    "Time of Purchase",
    "Departure Time",
    "Arrival Time",
    "Actual Arrival Time"
]].head(10)

  Time of Purchase Departure Time Arrival Time Actual Arrival Time
0         12:41:11       11:00:00     13:30:00            13:30:00
1         11:23:01       09:45:00     11:35:00            11:40:00
2         19:51:27       18:15:00     18:45:00            18:45:00
3         23:00:36       21:30:00     22:30:00            22:30:00
4         18:22:56       16:45:00     19:00:00            19:00:00
5         07:56:06       06:15:00     08:05:00            08:05:00
6         00:02:01       22:30:00     23:40:00            23:40:00
7         01:35:18       00:00:00     00:30:00            00:30:00
8         01:43:09       00:00:00     01:50:00            02:07:00
9         03:05:52       01:30:00     02:30:00            02:30:00

In [70]:
pd.crosstab(df["Journey Status"], df["Refund Request"])

Refund Request     No  Yes
Journey Status
Cancelled        1308  572
Delayed          1746  546
On Time         27481    0

In [71]:
df.loc[
    df["Journey Status"] == "Delayed",
    "Reason for Delay"
].value_counts(dropna=False)

Reason for Delay
Weather               758
Technical Issue       472
Signal Failure        242
Signal failure        209
Staff Shortage        183
Staffing              172
Weather Conditions    169
Traffic                87
Name: count, dtype: int64

In [72]:
df.loc[
    df["Journey Status"] == "Cancelled",
    "Reason for Delay"
].value_counts(dropna=False)

Reason for Delay
Signal Failure        281
Staffing              238
Signal failure        238
Weather               237
Technical Issue       235
Traffic               227
Staff Shortage        216
Weather Conditions    208
Name: count, dtype: int64

In [73]:
df["Reason for Delay"].dropna().sort_values().unique()

array(['Signal Failure', 'Signal failure', 'Staff Shortage', 'Staffing',
       'Technical Issue', 'Traffic', 'Weather', 'Weather Conditions'],
      dtype=object)

In [74]:
df["Reason for Delay"] = df["Reason for Delay"].str.title()

In [75]:
df["Reason for Delay"].value_counts(dropna=False)

Reason for Delay
NaN                   27481
Weather                 995
Signal Failure          970
Technical Issue         707
Staffing                410
Staff Shortage          399
Weather Conditions      377
Traffic                 314
Name: count, dtype: int64

In [76]:
pd.crosstab(df["Purchase Type"], df["Railcard"], dropna=False)

Railcard       Adult  Disabled  Senior    NaN
Purchase Type
Online          2213      2176    2221  11911
Station         2633       913     579   9007

In [77]:
pd.crosstab(df["Ticket Type"], df["Railcard"], dropna=False)

Railcard     Adult  Disabled  Senior    NaN
Ticket Type
Advance       2711      1661    1564  11625
Anytime        811       549     609   3371
Off-Peak      1324       879     627   5922

In [78]:
df["Departure Station"].sort_values().unique()

array(['Birmingham New Street', 'Bristol Temple Meads',
       'Edinburgh Waverley', 'Liverpool Lime Street', 'London Euston',
       'London Kings Cross', 'London Paddington', 'London St Pancras',
       'Manchester Piccadilly', 'Oxford', 'Reading', 'York'], dtype=object)

In [79]:
df["Arrival Destination"].sort_values().unique()

array(['Birmingham New Street', 'Bristol Temple Meads', 'Cardiff Central',
       'Coventry', 'Crewe', 'Didcot', 'Doncaster', 'Durham', 'Edinburgh',
       'Edinburgh Waverley', 'Leeds', 'Leicester',
       'Liverpool Lime Street', 'London Euston', 'London Kings Cross',
       'London Paddington', 'London St Pancras', 'London Waterloo',
       'Manchester Piccadilly', 'Nottingham', 'Nuneaton', 'Oxford',
       'Peterborough', 'Reading', 'Sheffield', 'Stafford', 'Swindon',
       'Tamworth', 'Wakefield', 'Warrington', 'Wolverhampton', 'York'],
      dtype=object)

In [80]:
df["Price"].value_counts().sort_index()

Price
1        16
2      1861
3      3468
4      1882
5      1580
       ...
216       6
235      20
238       2
242       2
267       3
Name: count, Length: 125, dtype: int64

In [81]:
departure_stations = set(df["Departure Station"].dropna().unique())
arrival_stations = set(df["Arrival Destination"].dropna().unique())

print("Departure stations:", len(departure_stations))
print("Arrival destinations:", len(arrival_stations))

print("\nStations only in Departure:")
print(departure_stations - arrival_stations)

print("\nStations only in Arrival:")
print(arrival_stations - departure_stations)

Departure stations: 12
Arrival destinations: 32

Stations only in Departure:
set()

Stations only in Arrival:
{'Warrington', 'Doncaster', 'Peterborough', 'Cardiff Central', 'Crewe', 'Stafford', 'Nottingham', 'Edinburgh', 'Wakefield', 'Durham', 'Coventry', 'Wolverhampton', 'Swindon', 'Sheffield', 'Leeds', 'London Waterloo', 'Nuneaton', 'Tamworth', 'Didcot', 'Leicester'}

In [82]:
df.groupby(["Ticket Type", "Ticket Class"])["Price"].describe()

                            count       mean        std  min    25%   50%  \
Ticket Type Ticket Class
Advance     First Class    1764.0  37.917234  28.376849  4.0  10.00  35.0
            Standard      15797.0  15.343926  18.655665  1.0   3.00   8.0
Anytime     First Class     490.0  77.226531  58.586937  8.0  21.25  69.0
            Standard       4850.0  35.354227  40.967867  2.0   9.00  16.0
Off-Peak    First Class     804.0  55.562189  42.001985  6.0  15.00  52.0
            Standard       7948.0  22.479366  27.439545  2.0   5.00  12.0

                            75%    max
Ticket Type Ticket Class
Advance     First Class    54.0  135.0
            Standard       16.0   86.0
Anytime     First Class   107.0  267.0
            Standard       47.0  171.0
Off-Peak    First Class    80.0  203.0
            Standard       22.0  128.0

In [83]:
price_Q1 = df["Price"].quantile(0.25)
price_Q3 = df["Price"].quantile(0.75)

price_IQR = price_Q3 - price_Q1

price_LWRB = price_Q1 - 1.5 * price_IQR
price_UPPB = price_Q3 + 1.5 * price_IQR

print("Lower Bound:", price_LWRB)
print("Upper Bound:", price_UPPB)

Lower Bound: -40.0
Upper Bound: 80.0

In [84]:
price_outlier_count = (
    (df["Price"] < price_LWRB) |
    (df["Price"] > price_UPPB)
).sum()

price_outlier_percentage = (
    price_outlier_count / len(df)
) * 100

print("Number of Price Outliers:", price_outlier_count)
print(f"Price Outliers Percentage: {price_outlier_percentage:.2f}%")

Number of Price Outliers: 1555
Price Outliers Percentage: 4.91%

In [85]:
df[
    (df["Price"] < price_LWRB) |
    (df["Price"] > price_UPPB)
][
    ["Price", "Ticket Type", "Ticket Class", "Purchase Type"]
].head(10)

     Price Ticket Type Ticket Class Purchase Type
25      86     Advance     Standard        Online
45     134     Advance  First Class       Station
51     151     Anytime     Standard       Station
61     134     Advance  First Class       Station
68     151     Anytime     Standard       Station
88      84    Off-Peak     Standard       Station
101    200    Off-Peak  First Class       Station
105     86     Advance     Standard        Online
129    107     Anytime  First Class       Station
130     84     Advance     Standard       Station

In [86]:
for (ticket_type, ticket_class), group in df.groupby(
    ["Ticket Type", "Ticket Class"] ):

    price_Q1 = group["Price"].quantile(0.25)
    price_Q3 = group["Price"].quantile(0.75)

    price_IQR = price_Q3 - price_Q1

    price_UPPB = price_Q3 + 1.5 * price_IQR
    price_LWRB = price_Q1 - 1.5 * price_IQR

    outlier_count = (
        (group["Price"] < price_LWRB) |
        (group["Price"] > price_UPPB)
    ).sum()

    outlier_percentage = (outlier_count / len(group)) * 100

    print(ticket_type, "-", ticket_class)
    print("Lower Bound:", price_LWRB)
    print("Upper Bound:", price_UPPB)
    print("Outliers:", outlier_count)
    print(f"Outliers Percentage: {outlier_percentage:.2f}%")
    print("=" * 40)

Advance - First Class
Lower Bound: -56.0
Upper Bound: 120.0
Outliers: 22
Outliers Percentage: 1.25%
========================================
Advance - Standard
Lower Bound: -16.5
Upper Bound: 35.5
Outliers: 1277
Outliers Percentage: 8.08%
========================================
Anytime - First Class
Lower Bound: -107.375
Upper Bound: 235.625
Outliers: 7
Outliers Percentage: 1.43%
========================================
Anytime - Standard
Lower Bound: -48.0
Upper Bound: 104.0
Outliers: 397
Outliers Percentage: 8.19%
========================================
Off-Peak - First Class
Lower Bound: -82.5
Upper Bound: 177.5
Outliers: 16
Outliers Percentage: 1.99%
========================================
Off-Peak - Standard
Lower Bound: -20.5
Upper Bound: 47.5
Outliers: 1491
Outliers Percentage: 18.76%
========================================

In [87]:
off_peak_standard = df[
    (df["Ticket Type"] == "Off-Peak") &
    (df["Ticket Class"] == "Standard")
]

off_peak_standard[
    ["Price", "Purchase Type", "Payment Method", "Railcard"]
].sort_values("Price", ascending=False).head(10)

       Price Purchase Type Payment Method Railcard
25931    128        Online    Credit Card      NaN
20195    128        Online    Credit Card      NaN
20329    128        Online    Credit Card      NaN
30441    128        Online    Credit Card      NaN
26626    128        Online    Credit Card      NaN
6158     128        Online    Credit Card      NaN
25525    128        Online    Credit Card      NaN
18370    128        Online    Credit Card      NaN
20480    128        Online    Credit Card      NaN
15735    128        Online    Credit Card      NaN

In [88]:
pd.crosstab(
    [df["Ticket Type"], df["Ticket Class"]],
    df["Railcard"],
    dropna=False
)

Railcard                  Adult  Disabled  Senior    NaN
Ticket Type Ticket Class
Advance     First Class     291       172     170   1131
            Standard       2420      1489    1394  10494
Anytime     First Class      83        56      55    296
            Standard        728       493     554   3075
Off-Peak    First Class     116        86      44    558
            Standard       1208       793     583   5364

In [89]:
df.groupby(
    ["Ticket Type", "Ticket Class", "Railcard"],
    dropna=False
)["Price"].agg(["count", "mean", "median"]).round(2)

                                   count   mean  median
Ticket Type Ticket Class Railcard
Advance     First Class  Adult       291  29.30    34.0
                         Disabled    172  30.91    35.0
                         Senior      170  15.93     7.0
                         NaN        1131  44.51    52.0
            Standard     Adult      2420  11.51     5.0
                         Disabled   1489  10.22     5.0
                         Senior     1394   7.04     2.0
                         NaN       10494  18.06     8.0
Anytime     First Class  Adult        83  63.08    69.0
                         Disabled     56  83.45    78.0
                         Senior       55  29.05    13.0
                         NaN         296  88.97   103.0
            Standard     Adult       728  24.11    11.0
                         Disabled    493  28.58    29.0
                         Senior      554  13.35    11.0
                         NaN        3075  43.07    25.0
Off-Peak    First Class  Adult       116  38.95    29.0
                         Disabled     86  37.63    49.5
                         Senior       44  29.34    10.0
                         NaN         558  63.85    78.0
            Standard     Adult      1208  18.75     8.0
                         Disabled    793  12.29     7.0
                         Senior      583  11.67     3.0
                         NaN        5364  26.00    12.0

In [90]:
df.groupby(
    ["Purchase Type", "Ticket Type", "Ticket Class"]
)["Price"].agg(["count", "mean", "median"]).round(2)

                                        count   mean  median
Purchase Type Ticket Type Ticket Class
Online        Advance     First Class    1040  34.47    32.0
                          Standard       9298  13.42     8.0
              Anytime     First Class     295  64.89    54.0
                          Standard       3036  28.50    17.0
              Off-Peak    First Class     446  55.07    52.0
                          Standard       4406  20.85    12.0
Station       Advance     First Class     724  42.86    35.0
                          Standard       6499  18.10     8.0
              Anytime     First Class     195  95.88    71.0
                          Standard       1814  46.82    16.0
              Off-Peak    First Class     358  56.18    45.0
                          Standard       3542  24.50    12.0

In [91]:
df.groupby(
    [
        "Purchase Type", "Ticket Type" , "Ticket Class" ,"Railcard"
    ],
    dropna=False
)["Price"].agg(["count", "mean", "median"]).round(2)

                                                 count    mean  median
Purchase Type Ticket Type Ticket Class Railcard
Online        Advance     First Class  Adult       127   22.28    13.0
                                       Disabled    129   32.77    35.0
                                       Senior      133   14.24     7.0
                                       NaN         651   41.33    52.0
                          Standard     Adult      1146    7.79     2.0
                                       Disabled   1031   12.06     8.0
                                       Senior     1112    6.75     3.0
                                       NaN        6009   15.96     8.0
              Anytime     First Class  Adult        30   36.67    27.0
                                       Disabled     42   82.86    78.0
                                       Senior       49   24.39    13.0
                                       NaN         174   76.83    63.0
                          Standard     Adult       311   16.96     9.0
                                       Disabled    337   35.55    29.0
                                       Senior      508   12.86    11.0
                                       NaN        1880   33.38    25.0
              Off-Peak    First Class  Adult        52   32.77    27.0
                                       Disabled     59   38.86    52.0
                                       Senior       32   27.22    10.0
                                       NaN         303   64.99    78.0
                          Standard     Adult       547   14.04     8.0
                                       Disabled    578   13.92     8.0
                                       Senior      387   11.07     5.0
                                       NaN        2894   24.83    12.0
Station       Advance     First Class  Adult       164   34.73    35.0
                                       Disabled     43   25.33    35.0
                                       Senior       37   22.00     6.0
                                       NaN         480   48.82    54.0
                          Standard     Adult      1274   14.86     6.0
                                       Disabled    458    6.07     4.0
                                       Senior      282    8.20     2.0
                                       NaN        4485   20.87     8.0
              Anytime     First Class  Adult        53   78.04    69.0
                                       Disabled     14   85.21    69.0
                                       Senior        6   67.17    44.5
                                       NaN         122  106.27   107.0
                          Standard     Adult       417   29.44    11.0
                                       Disabled    156   13.52     9.0
                                       Senior       46   18.83     3.0
                                       NaN        1195   58.31    25.0
              Off-Peak    First Class  Adult        64   43.97    42.5
                                       Disabled     27   34.93    27.0
                                       Senior       12   35.00    10.0
                                       NaN         255   62.49    54.0
                          Standard     Adult       661   22.64    10.0
                                       Disabled    215    7.90     3.0
                                       Senior      196   12.85     3.0
                                       NaN        2470   27.37    12.0

In [92]:
pd.crosstab(
    df["Railcard"].isna(),
    df["Purchase Type"]
)

Purchase Type  Online  Station
Railcard
False            6610     4125
True            11911     9007

In [93]:
pd.crosstab(
    df["Railcard"].isna(),
    [df["Ticket Type"], df["Ticket Class"]],
    normalize="columns"
).round(2) * 100

Ticket Type      Advance              Anytime             Off-Peak
Ticket Class First Class Standard First Class Standard First Class Standard
Railcard
False               36.0     34.0        40.0     37.0        31.0     33.0
True                64.0     66.0        60.0     63.0        69.0     67.0

In [94]:
pd.crosstab(
    df["Actual Arrival Time"].isna(),
    df["Journey Status"]
)

Journey Status       Cancelled  Delayed  On Time
Actual Arrival Time
False                        0     2292    27481
True                      1880        0        0

In [95]:
df.loc[
    df["Journey Status"] == "Cancelled",
    ["Departure Time", "Arrival Time", "Actual Arrival Time"]
].head(10)

    Departure Time Arrival Time Actual Arrival Time
39        02:15:00     03:35:00                 NaN
75        16:00:00     17:20:00                 NaN
91        02:15:00     03:35:00                 NaN
111       05:00:00     06:20:00                 NaN
148       08:00:00     10:15:00                 NaN
149       08:00:00     10:15:00                 NaN
151       08:00:00     10:15:00                 NaN
153       08:00:00     10:15:00                 NaN
154       08:00:00     09:20:00                 NaN
156       08:00:00     10:15:00                 NaN

In [96]:
pd.crosstab(
    df["Reason for Delay"].fillna("Missing"),
    df["Journey Status"]
)

Journey Status      Cancelled  Delayed  On Time
Reason for Delay
Missing                     0        0    27481
Signal Failure            519      451        0
Staff Shortage            216      183        0
Staffing                  238      172        0
Technical Issue           235      472        0
Traffic                   227       87        0
Weather                   237      758        0
Weather Conditions        208      169        0

In [97]:
df["Reason for Delay"] = df["Reason for Delay"].fillna("No Delay")

In [98]:
df["Reason for Delay"].value_counts()

Reason for Delay
No Delay              27481
Weather                 995
Signal Failure          970
Technical Issue         707
Staffing                410
Staff Shortage          399
Weather Conditions      377
Traffic                 314
Name: count, dtype: int64

In [99]:
df["Reason for Delay"].dropna().unique()

array(['No Delay', 'Signal Failure', 'Technical Issue',
       'Weather Conditions', 'Weather', 'Staffing', 'Staff Shortage',
       'Traffic'], dtype=object)

In [100]:
pd.crosstab(
    df["Reason for Delay"],
    df["Ticket Class"]
).loc[
    ["Weather", "Weather Conditions", "Staffing", "Staff Shortage"]
]

Ticket Class        First Class  Standard
Reason for Delay
Weather                      95       900
Weather Conditions           33       344
Staffing                     38       372
Staff Shortage               42       357

In [101]:
pd.crosstab(
    df["Reason for Delay"],
    df["Ticket Type"]
).loc[
    ["Weather", "Weather Conditions", "Staffing", "Staff Shortage"]
]

Ticket Type         Advance  Anytime  Off-Peak
Reason for Delay
Weather                 545      289       161
Weather Conditions      202       65       110
Staffing                222       59       129
Staff Shortage          211       42       146

In [102]:
pd.crosstab(
    df["Reason for Delay"],
    df["Purchase Type"]
).loc[
    ["Weather", "Weather Conditions", "Staffing", "Staff Shortage"]
]

Purchase Type       Online  Station
Reason for Delay
Weather                188      807
Weather Conditions     166      211
Staffing               152      258
Staff Shortage         177      222

In [103]:
df[
    df["Reason for Delay"].isin([
        "Weather",
        "Weather Conditions",
        "Staffing",
        "Staff Shortage"
    ])
][
    [
        "Reason for Delay",
        "Journey Status",
        "Ticket Type",
        "Ticket Class",
        "Purchase Type",
        "Price",
        "Departure Station",
        "Arrival Destination"
    ]
].head(20)

,Reason for Delay,Journey Status,Ticket Type,Ticket Class,Purchase Type,Price,Departure Station,Arrival Destination
45,Weather Conditions,Delayed,Advance,First Class,Station,134,Manchester Piccadilly,London Euston
51,Weather,Delayed,Anytime,Standard,Station,151,Liverpool Lime Street,London Euston
61,Weather,Delayed,Advance,First Class,Station,134,Manchester Piccadilly,London Euston
101,Weather Conditions,Delayed,Off-Peak,First Class,Station,200,Manchester Piccadilly,London Euston
111,Staffing,Cancelled,Off-Peak,Standard,Station,12,London St Pancras,Birmingham New Street
130,Weather Conditions,Delayed,Advance,Standard,Station,84,Manchester Piccadilly,London Euston
148,Staff Shortage,Cancelled,Anytime,First Class,Station,235,Liverpool Lime Street,London Euston
149,Staff Shortage,Cancelled,Anytime,Standard,Station,151,Liverpool Lime Street,London Euston
151,Staff Shortage,Cancelled,Anytime,Standard,Station,151,Liverpool Lime Street,London Euston
153,Staff Shortage,Cancelled,Anytime,Standard,Station,151,Liverpool Lime Street,London Euston
156,Staff Shortage,Cancelled,Anytime,Standard,Station,151,Liverpool Lime Street,London Euston
186,Staff Shortage,Cancelled,Off-Peak,Standard,Station,35,London Kings Cross,York
191,Staff Shortage,Cancelled,Off-Peak,Standard,Station,35,London Kings Cross,York
202,Weather,Delayed,Advance,Standard,Station,76,Liverpool Lime Street,London Euston
203,Weather,Delayed,Advance,Standard,Station,76,Liverpool Lime Street,London Euston
204,Weather,Delayed,Advance,Standard,Station,76,Liverpool Lime Street,London Euston
224,Staffing,Cancelled,Off-Peak,Standard,Station,19,Reading,London Paddington
227,Staff Shortage,Delayed,Advance,Standard,Station,3,Manchester Piccadilly,Liverpool Lime Street
265,Staffing,Delayed,Advance,Standard,Station,76,Liverpool Lime Street,London Euston
272,Weather Conditions,Cancelled,Advance,Standard,Online,4,London Euston,Birmingham New Street

In [106]:
pd.crosstab(
    df["Reason for Delay"],
    df["Journey Status"]
).loc[
    ["Weather", "Weather Conditions", "Staffing", "Staff Shortage"]
]

Journey Status      Cancelled  Delayed  On Time
Reason for Delay
Weather                   237      758        0
Weather Conditions        208      169        0
Staffing                  238      172        0
Staff Shortage            216      183        0

In [108]:
(df["Date of Journey"] - df["Date of Purchase"]).dt.days.describe()

count    31653.000000
mean         1.655957
std          3.853255
min          0.000000
25%          0.000000
50%          1.000000
75%          1.000000
max         28.000000
dtype: float64

In [109]:
days_before_journey = ( df["Date of Journey"] - df["Date of Purchase"] ).dt.days

days_before_journey.value_counts().sort_index()

0     14092
1     13744
2       367
3       284
4       254
5       221
6       212
7       253
8       219
9       182
10      193
11      190
12      160
13      149
14      163
15      148
16      135
17      119
18      103
19       91
20       79
21       74
22       64
23       52
24       33
25       36
26       16
27       19
28        1
Name: count, dtype: int64

In [110]:
df[
    [
        "Time of Purchase",
        "Departure Time",
        "Arrival Time",
        "Actual Arrival Time"
    ]
].dtypes

Time of Purchase       object
Departure Time         object
Arrival Time           object
Actual Arrival Time    object
dtype: object

In [112]:
df.isnull().sum()

Transaction ID             0
Date of Purchase           0
Time of Purchase           0
Purchase Type              0
Payment Method             0
Railcard               20918
Ticket Class               0
Ticket Type                0
Price                      0
Departure Station          0
Arrival Destination        0
Date of Journey            0
Departure Time             0
Arrival Time               0
Actual Arrival Time     1880
Journey Status             0
Reason for Delay           0
Refund Request             0
dtype: int64

In [120]:
df_clean = df.copy()

In [122]:

df_clean.columns.tolist()

['Transaction ID',
 'Date of Purchase',
 'Time of Purchase',
 'Purchase Type',
 'Payment Method',
 'Railcard',
 'Ticket Class',
 'Ticket Type',
 'Price',
 'Departure Station',
 'Arrival Destination',
 'Date of Journey',
 'Departure Time',
 'Arrival Time',
 'Actual Arrival Time',
 'Journey Status',
 'Reason for Delay',
 'Refund Request']

In [127]:
df_clean["Railcard"].value_counts(dropna=False)

Railcard
NaN         20918
Adult        4846
Disabled     3089
Senior       2800
Name: count, dtype: int64

In [129]:
time_columns = [
    "Time of Purchase",
    "Departure Time",
    "Arrival Time",
    "Actual Arrival Time"
]

In [130]:
for col in time_columns:
    print("\n", col)
    print(df_clean[col].dropna().map(type).value_counts())

 Time of Purchase
Time of Purchase
<class 'datetime.time'>    31653
Name: count, dtype: int64

 Departure Time
Departure Time
<class 'datetime.time'>    31653
Name: count, dtype: int64

 Arrival Time
Arrival Time
<class 'datetime.time'>    31653
Name: count, dtype: int64

 Actual Arrival Time
Actual Arrival Time
<class 'datetime.time'>    29773
Name: count, dtype: int64

In [131]:
df_clean.duplicated().sum()

np.int64(0)

In [132]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31653 entries, 0 to 31652
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction ID       31653 non-null  object
 1   Date of Purchase     31653 non-null  datetime64[ns]
 2   Time of Purchase     31653 non-null  object
 3   Purchase Type        31653 non-null  object
 4   Payment Method       31653 non-null  object
 5   Railcard             10735 non-null  object
 6   Ticket Class         31653 non-null  object
 7   Ticket Type          31653 non-null  object
 8   Price                31653 non-null  int64
 9   Departure Station    31653 non-null  object
 10  Arrival Destination  31653 non-null  object
 11  Date of Journey      31653 non-null  datetime64[ns]
 12  Departure Time       31653 non-null  object
 13  Arrival Time         31653 non-null  object
 14  Actual Arrival Time  29773 non-null  object
 15  Journey Status       31653 non-null  object
 16  Reason for Delay     31653 non-null  object
 17  Refund Request       31653 non-null  object
dtypes: datetime64[ns](2), int64(1), object(15)
memory usage: 4.3+ MB

In [133]:
df_clean.isnull().sum()

Transaction ID             0
Date of Purchase           0
Time of Purchase           0
Purchase Type              0
Payment Method             0
Railcard               20918
Ticket Class               0
Ticket Type                0
Price                      0
Departure Station          0
Arrival Destination        0
Date of Journey            0
Departure Time             0
Arrival Time               0
Actual Arrival Time     1880
Journey Status             0
Reason for Delay           0
Refund Request             0
dtype: int64

In [134]:
# Data Model

print("Dataset represents railway ticket transactions.")
print("Each row represents one ticket transaction.")
print("Transaction ID is the unique identifier for each transaction.")

Dataset represents railway ticket transactions.
Each row represents one ticket transaction.
Transaction ID is the unique identifier for each transaction.

In [135]:
# Main Data Model Components

transaction_columns = [
    "Transaction ID",
    "Date of Purchase",
    "Time of Purchase",
    "Purchase Type",
    "Payment Method",
    "Railcard",
    "Price",
    "Refund Request"
]

journey_columns = [
    "Date of Journey",
    "Departure Time",
    "Arrival Time",
    "Actual Arrival Time",
    "Departure Station",
    "Arrival Destination",
    "Journey Status",
    "Reason for Delay"
]

ticket_columns = [
    "Ticket Class",
    "Ticket Type"
]

print("Transaction Information:")
print(transaction_columns)

print("\nJourney Information:")
print(journey_columns)

print("\nTicket Information:")
print(ticket_columns)

Transaction Information:
['Transaction ID', 'Date of Purchase', 'Time of Purchase', 'Purchase Type', 'Payment Method', 'Railcard', 'Price', 'Refund Request']

Journey Information:
['Date of Journey', 'Departure Time', 'Arrival Time', 'Actual Arrival Time', 'Departure Station', 'Arrival Destination', 'Journey Status', 'Reason for Delay']

Ticket Information:
['Ticket Class', 'Ticket Type']

In [136]:
df_clean["Transaction ID"].nunique()

31653

In [137]:
len(df_clean)

31653

In [139]:
# Save Cleaned Dataset

df_clean.to_csv(
    "data/cleaned/railway_clean.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!